Revised installation instructions
Dyalog/link pull request #673
Opened 2024-09-15 14:24 UTC by 5jt

-   enabled MkDocs features and extensions
-   revised installation instructions

**Not ready to merge**

First, revise Step 4 for Windows.

2024-09-24 12:21 UTC, 5jt commented
Revised for Windows. Tested with 19.0 on Windows 10 for default and custom install locations. Not tested for 18.2. FIXMEs remain for Other operating systems – AIX?

2025-02-04 10:12 UTC, rikedyp requested changes
Overall these changes make the installation procedure much clearer. I have the following minor comments.

1. I don't mind the inclusion of footnotes but the [^opensource] for Link 4.0 feels unnecessary. Fine to leave it in if you feel strongly that it's helpful.
2. Suggest replacing :fontawesome-brands-windows: with :simple-dotnet:
3. Remove operating system logos. At least the use of the Apple logo is not allowed; best to remove them all

2025-02-13 15:47 UTC, rikedyp commented
I'm asking about DyalogStartupSE locations on AIX. Other than that .NET is not supported so Link cannot watch for changes by external editors. I'll make these changes once I have info.

2025-02-18 11:36 UTC, rikedyp commented
So most AIX behaviour is Unix-Like, and so we now have "Linux, macOS, AIX" tabs except in the .NET section where .NET is not available for AIX

2025-02-18 11:40 UTC, merged